In [85]:
import pandas as pd
from io import StringIO
pd.set_option("display.max_columns", None)
#pd.set_option("display.max_rows", 100)

In [63]:
# Define the custom sorting order
custom_order_column1 = {
    'Facil': 0,
    'Media': 1,
    'Dificil': 2
}
custom_order_column2 = {
    'Mitologia Griega': 0,
    'Biblia': 1,
    'Mitologia Latina': 2,
    'Autores latinos': 3,
    'Cultura general': 4
}

In [79]:
df = pd.read_excel(r"C:/Users/chucp/Desktop/Work/BD Preguntas/Preguntas_de_la_trivia.xlsx")
df = df.dropna(how='all')
# Create a new column combining custom ordering for both columns
df['custom_order'] = df['Dificultad'].map(custom_order_column1).astype(str) + '_' + df['Categoria'].map(custom_order_column2).astype(str)
# Sort the DataFrame based on the new column
sorted_df = df.sort_values(by='custom_order')
#Drop the custom order column
sorted_df = sorted_df.drop('custom_order', axis=1)
sorted_df

,Preguntas,Respuesta Correctas,Alternativa 2 (Incorrecta),Alternativa 3 (Incorrecta),Alternativa 4 (Incorrecta),Categoria,Dificultad
0,¿Quién fue el héroe que mató a la hidra de Ler...,Hércules,Poseidón,Teseo,Ícaro,Mitologia Griega,Facil
1,¿Quién fue el héroe que mató al Minotauro en l...,Teseo,Hércules,Hydra,Ariadna,Mitologia Griega,Facil
2,¿Quién es el dios del mar en la mitología grie...,Poseidón,Neptuno,Saturno,Chronos,Mitologia Griega,Facil
3,¿Quién es el dios de la guerra en la mitología...,Ares,Kratos,Thor,Hades,Mitologia Griega,Facil
4,¿Quién es el dios del trueno en la mitología g...,Zeus,Thor,Ateneo,Odin,Mitologia Griega,Facil
...,...,...,...,...,...,...,...
113,¿Cuál es el título de la novela de Aldous Huxl...,Un mundo feliz,Don Quijote de la Mancha,La Odisea,Hamlet,Cultura general,Dificil
114,: ¿Cuál es el título de la novela gráfica de A...,Fun Home,En busca del tiempo perdido,1984,Moby-Dick,Cultura general,Dificil
115,¿Cuál es el título de la obra de teatro de Ton...,Ángeles en América,Don Quijote de la Mancha,La Odisea,Guerra y paz,Cultura general,Dificil
116,"¿Quién es el autor del libro ""El hombre bicent...",Isaac Asimov,Roberto Bolaño,E.L. James,Patrick Rothfuss,Cultura general,Dificil
117,¿Cuál es el título del libro de Louisa May Alc...,Little Women,Don Quijote de la Mancha,Hamlet,Cien años de soledad,Cultura general,Dificil

In [81]:
# Save the table values to a CSV file
sorted_df.to_csv('preguntas_ordenadas.csv', index=False)

# Save the table values to an Excel file
sorted_df.to_excel('preguntas_ordenadas_excel.xlsx', index=False)

In [86]:
sorted_df

,Preguntas,Respuesta Correctas,Alternativa 2 (Incorrecta),Alternativa 3 (Incorrecta),Alternativa 4 (Incorrecta),Categoria,Dificultad
0,¿Quién fue el héroe que mató a la hidra de Ler...,Hércules,Poseidón,Teseo,Ícaro,Mitologia Griega,Facil
1,¿Quién fue el héroe que mató al Minotauro en l...,Teseo,Hércules,Hydra,Ariadna,Mitologia Griega,Facil
2,¿Quién es el dios del mar en la mitología grie...,Poseidón,Neptuno,Saturno,Chronos,Mitologia Griega,Facil
3,¿Quién es el dios de la guerra en la mitología...,Ares,Kratos,Thor,Hades,Mitologia Griega,Facil
4,¿Quién es el dios del trueno en la mitología g...,Zeus,Thor,Ateneo,Odin,Mitologia Griega,Facil
...,...,...,...,...,...,...,...
113,¿Cuál es el título de la novela de Aldous Huxl...,Un mundo feliz,Don Quijote de la Mancha,La Odisea,Hamlet,Cultura general,Dificil
114,: ¿Cuál es el título de la novela gráfica de A...,Fun Home,En busca del tiempo perdido,1984,Moby-Dick,Cultura general,Dificil
115,¿Cuál es el título de la obra de teatro de Ton...,Ángeles en América,Don Quijote de la Mancha,La Odisea,Guerra y paz,Cultura general,Dificil
116,"¿Quién es el autor del libro ""El hombre bicent...",Isaac Asimov,Roberto Bolaño,E.L. James,Patrick Rothfuss,Cultura general,Dificil
117,¿Cuál es el título del libro de Louisa May Alc...,Little Women,Don Quijote de la Mancha,Hamlet,Cien años de soledad,Cultura general,Dificil